apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp-svc
  name: {{ .Release.Name }}-webapp-svc
spec:
  ports:
    - name: webapp-svc
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: assocapp
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
